kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-trigger
subjects:
- kind: ServiceAccount
  name: kube-trigger
roleRef:
  kind: Role
  name: kube-trigger
  apiGroup: rbac.authorization.k8s.io
