apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-trigger
  template:
    metadata:
      labels:
        name: kube-trigger
    spec:
      serviceAccountName: kube-trigger
      containers:
        - name: kube-trigger
          # Replace this with the built image name
          image: tong16/kube-trigger
          command:
          - kube-trigger
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kube-trigger"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-trigger
subjects:
- kind: ServiceAccount
  name: kube-trigger
roleRef:
  kind: Role
  name: kube-trigger
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kube-trigger
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - kube-trigger
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - app.example.com
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-trigger
subjects:
- kind: ServiceAccount
  name: kube-trigger
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube-trigger
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kube-trigger
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - kube-trigger
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - app.example.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-trigger
